description: Ubuntu 14.04 Desktop version that install all development tools with an provisioner shell script.
provision: shell
hint: The oracle jdk 8 installation is full automated and accept the license automated. To use npm perform su -l vagrant on the terminal.
username: vagrant
password: vagrant
